// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SdlcCopilot.Infrastructure.Persistence;

#nullable disable

namespace SdlcCopilot.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SdlcCopilot.Domain.Entities.AmbiguityFinding", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Excerpt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Issue")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer");

                    b.Property<Guid>("RequirementId")
                        .HasColumnType("uuid");

                    b.Property<int>("Severity")
                        .HasColumnType("integer");

                    b.Property<string>("Suggestion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RequirementId");

                    b.ToTable("ambiguities", (string)null);
                });

            modelBuilder.Entity("SdlcCopilot.Domain.Entities.Analysis", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Goals")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("KeyConstraints")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RawJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Guid>("RequirementId")
                        .HasColumnType("uuid");

                    b.Property<string>("Stakeholders")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RequirementId")
                        .IsUnique();

                    b.ToTable("analyses", (string)null);
                });

            modelBuilder.Entity("SdlcCopilot.Domain.Entities.ChatMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RequirementId")
                        .HasColumnType("uuid");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RequirementId");

                    b.ToTable("chat_messages", (string)null);
                });

            modelBuilder.Entity("SdlcCopilot.Domain.Entities.DevTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Complexity")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("EstimatedHours")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<string>("Layer")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer");

                    b.Property<Guid>("RequirementId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("UserStoryId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RequirementId");

                    b.HasIndex("UserStoryId");

                    b.ToTable("dev_tasks", (string)null);
                });

            modelBuilder.Entity("SdlcCopilot.Domain.Entities.Epic", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer");

                    b.Property<Guid>("RequirementId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("RequirementId");

                    b.ToTable("epics", (string)null);
                });

            modelBuilder.Entity("SdlcCopilot.Domain.Entities.Requirement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SourceFileName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("SourceText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("requirements", (string)null);
                });

            modelBuilder.Entity("SdlcCopilot.Domain.Entities.TestCase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExpectedResult")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Kind")
                        .HasColumnType("integer");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer");

                    b.Property<string>("Preconditions")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("RequirementId")
                        .HasColumnType("uuid");

                    b.Property<string>("StepsJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("UserStoryId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RequirementId");

                    b.HasIndex("UserStoryId");

                    b.ToTable("test_cases", (string)null);
                });

            modelBuilder.Entity("SdlcCopilot.Domain.Entities.UserStory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AcceptanceCriteriaJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("AsA")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Complexity")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("EpicId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("EstimatedHours")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<string>("IWant")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer");

                    b.Property<Guid>("RequirementId")
                        .HasColumnType("uuid");

                    b.Property<string>("SoThat")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("StoryPoints")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("EpicId");

                    b.HasIndex("RequirementId");

                    b.ToTable("user_stories", (string)null);
                });

            modelBuilder.Entity("SdlcCopilot.Domain.Entities.AmbiguityFinding", b =>
                {
                    b.HasOne("SdlcCopilot.Domain.Entities.Requirement", "Requirement")
                        .WithMany("Ambiguities")
                        .HasForeignKey("RequirementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Requirement");
                });

            modelBuilder.Entity("SdlcCopilot.Domain.Entities.Analysis", b =>
                {
                    b.HasOne("SdlcCopilot.Domain.Entities.Requirement", "Requirement")
                        .WithOne("Analysis")
                        .HasForeignKey("SdlcCopilot.Domain.Entities.Analysis", "RequirementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Requirement");
                });

            modelBuilder.Entity("SdlcCopilot.Domain.Entities.ChatMessage", b =>
                {
                    b.HasOne("SdlcCopilot.Domain.Entities.Requirement", "Requirement")
                        .WithMany("ChatMessages")
                        .HasForeignKey("RequirementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Requirement");
                });

            modelBuilder.Entity("SdlcCopilot.Domain.Entities.DevTask", b =>
                {
                    b.HasOne("SdlcCopilot.Domain.Entities.Requirement", "Requirement")
                        .WithMany("Tasks")
                        .HasForeignKey("RequirementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SdlcCopilot.Domain.Entities.UserStory", "UserStory")
                        .WithMany()
                        .HasForeignKey("UserStoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Requirement");

                    b.Navigation("UserStory");
                });

            modelBuilder.Entity("SdlcCopilot.Domain.Entities.Epic", b =>
                {
                    b.HasOne("SdlcCopilot.Domain.Entities.Requirement", "Requirement")
                        .WithMany("Epics")
                        .HasForeignKey("RequirementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Requirement");
                });

            modelBuilder.Entity("SdlcCopilot.Domain.Entities.TestCase", b =>
                {
                    b.HasOne("SdlcCopilot.Domain.Entities.Requirement", "Requirement")
                        .WithMany("TestCases")
                        .HasForeignKey("RequirementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SdlcCopilot.Domain.Entities.UserStory", "UserStory")
                        .WithMany()
                        .HasForeignKey("UserStoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Requirement");

                    b.Navigation("UserStory");
                });

            modelBuilder.Entity("SdlcCopilot.Domain.Entities.UserStory", b =>
                {
                    b.HasOne("SdlcCopilot.Domain.Entities.Epic", "Epic")
                        .WithMany("UserStories")
                        .HasForeignKey("EpicId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SdlcCopilot.Domain.Entities.Requirement", "Requirement")
                        .WithMany("UserStories")
                        .HasForeignKey("RequirementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Epic");

                    b.Navigation("Requirement");
                });

            modelBuilder.Entity("SdlcCopilot.Domain.Entities.Epic", b =>
                {
                    b.Navigation("UserStories");
                });

            modelBuilder.Entity("SdlcCopilot.Domain.Entities.Requirement", b =>
                {
                    b.Navigation("Ambiguities");

                    b.Navigation("Analysis");

                    b.Navigation("ChatMessages");

                    b.Navigation("Epics");

                    b.Navigation("Tasks");

                    b.Navigation("TestCases");

                    b.Navigation("UserStories");
                });
#pragma warning restore 612, 618
        }
    }
}
